2022-05-09 17:39:33,365 INFO    Thread-4  :50463 [wandb_setup.py:_flush():75] Loading settings from /home/diego/.config/wandb/settings
2022-05-09 17:39:33,365 INFO    Thread-4  :50463 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-05-09 17:39:33,365 INFO    Thread-4  :50463 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'console': 'off', 'root_dir': '/home/diego/counterfactuals-generation/sentiment_task/fine_tuning_experiments', 'sweep_id': 'n1rlby5m', 'entity': 'cdiego89', 'project': 'counterfactuals-generation', 'run_id': '0ld11jlb', 'sweep_param_path': '/home/diego/counterfactuals-generation/sentiment_task/fine_tuning_experiments/wandb/sweep-n1rlby5m/config-0ld11jlb.yaml'}
2022-05-09 17:39:33,365 INFO    Thread-4  :50463 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'wandb_gpt2_gen_tuning.py', 'program': '/home/diego/counterfactuals-generation/sentiment_task/fine_tuning_experiments/wandb_gpt2_gen_tuning.py'}
2022-05-09 17:39:33,366 INFO    Thread-4  :50463 [wandb_setup.py:_flush():75] Applying settings from <Settings {'_args': None, '_cli_only_mode': None, '_colab': False, '_config_dict': None, '_console': <SettingsConsole.OFF: 0>, '_cuda': None, '_disable_meta': None, '_disable_stats': None, '_disable_viewer': None, '_except_exit': None, '_executable': None, '_internal_check_process': 8, '_internal_queue_timeout': 2, '_jupyter': False, '_jupyter_name': None, '_jupyter_path': None, '_jupyter_root': None, '_kaggle': False, '_noop': False, '_offline': False, '_os': None, '_platform': 'linux', '_python': None, '_require_service': None, '_runqueue_item_id': None, '_save_requirements': True, '_service_transport': None, '_start_datetime': None, '_start_time': None, '_tmp_code_dir': 'wandb/run-None-None/tmp/code', '_tracelog': None, '_unsaved_keys': None, '_windows': False, 'allow_val_change': None, 'anonymous': None, 'api_key': '***REDACTED***', 'base_url': 'https://api.wandb.ai', 'code_dir': None, 'config_paths': None, 'console': 'off', 'deployment': 'cloud', 'disable_code': None, 'disable_git': None, 'disabled': False, 'docker': None, 'email': None, 'entity': None, 'files_dir': 'wandb/run-None-None/files', 'force': None, 'git_remote': 'origin', 'heartbeat_seconds': 30, 'host': None, 'ignore_globs': (), 'is_local': False, 'label_disable': None, 'launch': None, 'launch_config_path': None, 'log_dir': 'wandb/run-None-None/logs', 'log_internal': 'wandb/run-None-None/logs/debug-internal.log', 'log_symlink_internal': 'wandb/debug-internal.log', 'log_symlink_user': 'wandb/debug.log', 'log_user': 'wandb/run-None-None/logs/debug.log', 'login_timeout': None, 'magic': None, 'mode': 'online', 'notebook_name': None, 'problem': 'fatal', 'program': None, 'program_relpath': None, 'project': None, 'project_url': '', 'quiet': None, 'reinit': None, 'relogin': None, 'resume': None, 'resume_fname': 'wandb/wandb-resume.json', 'resumed': False, 'root_dir': None, 'run_group': None, 'run_id': None, 'run_job_type': None, 'run_mode': 'run', 'run_name': None, 'run_notes': None, 'run_tags': None, 'run_url': '', 'sagemaker_disable': None, 'save_code': None, 'settings_system': '/home/diego/.config/wandb/settings', 'settings_workspace': 'wandb/settings', 'show_colors': None, 'show_emoji': None, 'show_errors': True, 'show_info': True, 'show_warnings': True, 'silent': False, 'start_method': None, 'strict': None, 'summary_errors': None, 'summary_warnings': 5, 'sweep_id': None, 'sweep_param_path': None, 'sweep_url': '', 'symlink': None, 'sync_dir': 'wandb/run-None-None', 'sync_file': 'wandb/run-None-None/run-None.wandb', 'sync_symlink_latest': 'wandb/latest-run', 'system_sample': 15, 'system_sample_seconds': 2, 'timespec': None, 'tmp_dir': 'wandb/run-None-None/tmp', 'username': None, 'wandb_dir': 'wandb/'}>
2022-05-09 17:39:33,366 INFO    Thread-4  :50463 [wandb_init.py:_log_setup():438] Logging user logs to /home/diego/counterfactuals-generation/sentiment_task/fine_tuning_experiments/wandb/run-20220509_173933-0ld11jlb/logs/debug.log
2022-05-09 17:39:33,366 INFO    Thread-4  :50463 [wandb_init.py:_log_setup():439] Logging internal logs to /home/diego/counterfactuals-generation/sentiment_task/fine_tuning_experiments/wandb/run-20220509_173933-0ld11jlb/logs/debug-internal.log
2022-05-09 17:39:33,366 INFO    Thread-4  :50463 [wandb_init.py:init():472] calling init triggers
2022-05-09 17:39:33,366 INFO    Thread-4  :50463 [wandb_init.py:init():476] wandb.init called with sweep_config: {'no_repeat_ngram_size': 3, 'num_beams': 1, 'repetition_penalty': 0.8518749113595381, 'temperature': 1.3655821316862622}
config: {}
2022-05-09 17:39:33,366 INFO    Thread-4  :50463 [wandb_init.py:init():525] starting backend
2022-05-09 17:39:33,366 INFO    Thread-4  :50463 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-05-09 17:39:33,387 INFO    Thread-4  :50463 [backend.py:ensure_launched():219] starting backend process...
2022-05-09 17:39:33,404 INFO    Thread-4  :50463 [backend.py:ensure_launched():225] started backend process with pid: 51186
2022-05-09 17:39:33,405 INFO    Thread-4  :50463 [wandb_init.py:init():534] backend started and connected
2022-05-09 17:39:33,410 INFO    Thread-4  :50463 [wandb_run.py:_config_callback():1129] config_cb None None {'no_repeat_ngram_size': 3, 'num_beams': 1, 'repetition_penalty': 0.8518749113595381, 'temperature': 1.3655821316862622}
2022-05-09 17:39:33,415 INFO    Thread-4  :50463 [wandb_init.py:init():598] updated telemetry
2022-05-09 17:39:33,415 INFO    Thread-4  :50463 [wandb_init.py:init():629] communicating run to backend with 30 second timeout
2022-05-09 17:39:34,969 INFO    Thread-4  :50463 [wandb_run.py:_on_init():1922] communicating current version
2022-05-09 17:39:35,010 INFO    Thread-4  :50463 [wandb_run.py:_on_init():1926] got version response upgrade_message: "wandb version 0.12.16 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-05-09 17:39:35,010 INFO    Thread-4  :50463 [wandb_init.py:init():660] starting run threads in backend
2022-05-09 17:39:36,751 INFO    Thread-4  :50463 [wandb_run.py:_console_start():1896] atexit reg
2022-05-09 17:39:36,752 INFO    Thread-4  :50463 [wandb_run.py:_redirect():1769] redirect: SettingsConsole.OFF
2022-05-09 17:39:36,752 INFO    Thread-4  :50463 [wandb_init.py:init():685] run started, returning control to user process
2022-05-09 17:42:34,782 INFO    Thread-4  :50463 [wandb_run.py:_finish():1684] finishing run cdiego89/counterfactuals-generation/0ld11jlb
2022-05-09 17:42:34,782 INFO    Thread-4  :50463 [wandb_run.py:_atexit_cleanup():1865] got exitcode: 0
2022-05-09 17:42:34,782 INFO    Thread-4  :50463 [wandb_run.py:_restore():1837] restore
2022-05-09 17:42:34,792 INFO    Thread-4  :50463 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 959
  total_bytes: 959
}

2022-05-09 17:42:35,082 INFO    Thread-4  :50463 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 959
  total_bytes: 959
}

2022-05-09 17:42:36,029 INFO    Thread-4  :50463 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 959
  total_bytes: 1876
}

2022-05-09 17:42:36,132 INFO    Thread-4  :50463 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 959
  total_bytes: 10870
}

2022-05-09 17:42:36,235 INFO    Thread-4  :50463 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 959
  total_bytes: 10870
}

2022-05-09 17:42:36,338 INFO    Thread-4  :50463 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10870
  total_bytes: 10870
}

2022-05-09 17:42:36,441 INFO    Thread-4  :50463 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10870
  total_bytes: 10870
}

2022-05-09 17:42:36,544 INFO    Thread-4  :50463 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10870
  total_bytes: 10870
}

2022-05-09 17:42:36,648 INFO    Thread-4  :50463 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10870
  total_bytes: 10870
}

2022-05-09 17:42:36,752 INFO    Thread-4  :50463 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10870
  total_bytes: 10870
}

2022-05-09 17:42:36,855 INFO    Thread-4  :50463 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10870
  total_bytes: 10870
}

2022-05-09 17:42:37,572 INFO    Thread-4  :50463 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10870
  total_bytes: 10870
}

2022-05-09 17:42:38,082 INFO    Thread-4  :50463 [wandb_run.py:_on_finish():1995] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10870
  total_bytes: 10870
}
local_info {
}

2022-05-09 17:42:39,235 INFO    Thread-4  :50463 [wandb_run.py:_footer_history_summary_info():3087] rendering history
2022-05-09 17:42:39,235 INFO    Thread-4  :50463 [wandb_run.py:_footer_history_summary_info():3116] rendering summary
2022-05-09 17:42:39,236 INFO    Thread-4  :50463 [wandb_run.py:_footer_sync_info():3044] logging synced files
